#+title: A Kiss
#+author: levinhne

Carlos buys a new car (/kär/). [[file:Its.org][It's]]  a very expensive[fn:1] car. It's a huge[fn:2], blue, fast car.

While[fn:3] driving down on the street, Carlos sees a girl on a bicycle. She [[file:has.org][has]] long blond hair and is beautiful.

He yells[fn:4] to her, "What's up?[fn:5]"

She ignores [[file:him.org][him]].

He yells, "How's it going?[fn:6]"

She keeps going[fn:7] and ignores him.

He yells, "Hey, why won't you talk to me? I want to go to dinner with you. I'll take you to an expensive restraurant."

The girl turns, gets off the bike, and looks at him.

She says, "I don't want to go to dinner. But if you give me your car, I will give you a surprise."

Caslos says, "OK!" He jumps out of the car. He give ger the keys and says, "Here are the keys."

The beautiful blond takes the keys and then kisses Carlos on the cheek. Then she jumps into the car and drives away.

Calos stands on the sidewalk. Now he has no car and no girl.

He says, "That's it, just a kiss on the cheek?"

He gets on her bike and rides home.

* Footnotes

[fn:7] keeps going: tiếp tục đi

[fn:6] how's it going?: mọi việc thế nào rồi?

[fn:5] what's up?: có chuyện gì thế?

[fn:4] yells: la hét

[fn:3] while: trong khi

[fn:2] huge: rất to, rất lớn

[fn:1] expensive: đắt, đắt tiền
